CREATE TABLE noshow_records (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    reservation_id BIGINT NOT NULL COMMENT '预约ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    user_name VARCHAR(50) NOT NULL COMMENT '用户姓名',
    user_phone VARCHAR(20) NOT NULL COMMENT '用户手机号',
    venue_id BIGINT NOT NULL COMMENT '场地ID',
    venue_name VARCHAR(100) NOT NULL COMMENT '场地名称',
    venue_type VARCHAR(50) NOT NULL COMMENT '场地类型',
    date DATE NOT NULL COMMENT '预约日期',
    time_range VARCHAR(50) NOT NULL COMMENT '时间段',
    number_of_people INT NOT NULL COMMENT '预约人数',
    cost DECIMAL(10,2) NOT NULL COMMENT '预约费用',
    status VARCHAR(20) NOT NULL COMMENT '状态：PENDING-待处理，EXCUSED-已免责，PENALIZED-已处罚',
    penalty DECIMAL(10,2) COMMENT '违约金',
    restrict_days INT COMMENT '限制预约天数',
    handler VARCHAR(50) COMMENT '处理人',
    handle_time DATETIME COMMENT '处理时间',
    reason TEXT COMMENT '处理原因',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_reservation_id (reservation_id),
    INDEX idx_user_id (user_id),
    INDEX idx_venue_id (venue_id),
    INDEX idx_date (date),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='失约记录表'; 