server:
  port: 5678

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/gym_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      username: root
      password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

mybatis-plus:
  type-aliases-package: com.gymsys.domain.entity
  type-handlers-package: com.gymsys.handler
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_empty
  configuration:
    call-setters-on-nulls: true # 解决查询字段值为null而不显示的问题
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  issuer: gymsys
  secret: com.gymsys
  expiration: 999999999


