server:
  port: 5678

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/gymsys?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      username: root
      password: 123456

mybatis-plus:
  type-aliases-package: com.gymsys.domain.entity
  type-handlers-package: com.gymsys.handler
  global-config:
    db-config:
      id-type: auto
  configuration:
    call-setters-on-nulls: true # 解决查询字段值为null而不显示的问题
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl